### ISSUE TITLE
can't register

### ISSUE THREAD

**Issue by toejough** [neurosnap/youhood#21]
![image](https://user-images.githubusercontent.com/5317312/38965294-d7cce694-4349-11e8-8389-7d16124eef00.png)

*Given*

* user's not signed in

*When* 

* user clicks the sign in menu item
* user clicks the register button in the sign-in drop-down (without filling email or password)

*Expected Behavior*

* registration begins

*Actual Behavior*

* error message shown

**Comment by neurosnap** [comment]
This is probably a UX thing but registration is the same as sign in.  There is no other menu, all I require for registration is email and password.

Maybe I'll split the sign in and registration sections so it is more clear.  So the nav with have "Registration" and "Sign In"

**Comment by toejough** [comment]
a clearer error message would be a great first step, and likely sufficient for quite a while.  "Enter a username and password to register" instead of what looks like a raw backend failure message.
