### ISSUE TITLE
no way to pan when using creation tool

### ISSUE THREAD

**Issue by toejough** [neurosnap/youhood#25]
I'm not sure how to pan when using the creation tool.

If I swipe up or down or side-to-side (macbook pro touchpad, chrome), the map zooms, as if I were pinching/expanding.  If I click, it just adds a neighborhood boundary.

**Comment by neurosnap** [comment]
This one is going to be tricky.

**Comment by toejough** [comment]
not sure how tricky it would be, but maybe if you get within `n` pixels of the border, the map auto-pans?

**Comment by neurosnap** [comment]
I think for now this is a polish feature that we will not work on for now.
